const fs = require('fs');

const APPROVED_COLLEGES = [
  {"name":"IIT Bombay","city":"Mumbai","state":"Maharashtra","domain":"iitb.ac.in"},
  {"name":"IIT Delhi","city":"New Delhi","state":"Delhi","domain":"iitd.ac.in"},
  {"name":"IIT Madras","city":"Chennai","state":"Tamil Nadu","domain":"iitm.ac.in"},
  {"name":"IIT Kanpur","city":"Kanpur","state":"Uttar Pradesh","domain":"iitk.ac.in"},
  {"name":"IIT Kharagpur","city":"Kharagpur","state":"West Bengal","domain":"iitkgp.ac.in"},
  {"name":"IIT Roorkee","city":"Roorkee","state":"Uttarakhand","domain":"iitr.ac.in"},
  {"name":"IIT Guwahati","city":"Guwahati","state":"Assam","domain":"iitg.ac.in"},
  {"name":"IIT Hyderabad","city":"Hyderabad","state":"Telangana","domain":"iith.ac.in"},
  {"name":"IIT BHU","city":"Varanasi","state":"Uttar Pradesh","domain":"iitbhu.ac.in"},
  {"name":"IIT Indore","city":"Indore","state":"Madhya Pradesh","domain":"iiti.ac.in"},
  {"name":"NIT Trichy","city":"Tiruchirappalli","state":"Tamil Nadu","domain":"nitt.edu"},
  {"name":"NIT Surathkal","city":"Mangalore","state":"Karnataka","domain":"nitk.edu.in"},
  {"name":"NIT Warangal","city":"Warangal","state":"Telangana","domain":"nitw.ac.in"},
  {"name":"NIT Calicut","city":"Kozhikode","state":"Kerala","domain":"nitc.ac.in"},
  {"name":"NIT Rourkela","city":"Rourkela","state":"Odisha","domain":"nitrkl.ac.in"},
  {"name":"NIT Patna","city":"Patna","state":"Bihar","domain":"nitp.ac.in"},
  {"name":"NIT Durgapur","city":"Durgapur","state":"West Bengal","domain":"nitdgp.ac.in"},
  {"name":"NIT Silchar","city":"Silchar","state":"Assam","domain":"nits.ac.in"},
  {"name":"IIIT Hyderabad","city":"Hyderabad","state":"Telangana","domain":"iiit.ac.in"},
  {"name":"IIIT Bangalore","city":"Bangalore","state":"Karnataka","domain":"iiitb.ac.in"},
  {"name":"IIIT Delhi","city":"Delhi","state":"Delhi","domain":"iiitd.ac.in"},
  {"name":"IIIT Allahabad","city":"Prayagraj","state":"Uttar Pradesh","domain":"iiita.ac.in"},
  {"name":"BITS Pilani","city":"Pilani","state":"Rajasthan","domain":"pilani.bits-pilani.ac.in"},
  {"name":"BITS Goa","city":"Goa","state":"Goa","domain":"goa.bits-pilani.ac.in"},
  {"name":"BITS Hyderabad","city":"Hyderabad","state":"Telangana","domain":"hyderabad.bits-pilani.ac.in"},
  {"name":"VIT Vellore","city":"Vellore","state":"Tamil Nadu","domain":"vitstudent.ac.in"},
  {"name":"SRM Institute","city":"Chennai","state":"Tamil Nadu","domain":"srmist.edu.in"},
  {"name":"Manipal Institute","city":"Manipal","state":"Karnataka","domain":"learner.manipal.edu"},
  {"name":"KIIT","city":"Bhubaneswar","state":"Odisha","domain":"kiit.ac.in"},
  {"name":"DTU","city":"Delhi","state":"Delhi","domain":"dtu.ac.in"},
  {"name":"NSUT","city":"Delhi","state":"Delhi","domain":"nsut.ac.in"},
  {"name":"Jadavpur University","city":"Kolkata","state":"West Bengal","domain":"jadavpuruniversity.in"},
  {"name":"Anna University","city":"Chennai","state":"Tamil Nadu","domain":"annauniv.edu"},
  {"name":"COEP","city":"Pune","state":"Maharashtra","domain":"coep.ac.in"},
  {"name":"RV College of Engineering","city":"Bangalore","state":"Karnataka","domain":"rvce.edu.in"},
  {"name":"BMS College of Engineering","city":"Bangalore","state":"Karnataka","domain":"bmsce.ac.in"},
  {"name":"MS Ramaiah Institute","city":"Bangalore","state":"Karnataka","domain":"msrit.edu"},
  {"name":"PES University","city":"Bangalore","state":"Karnataka","domain":"pes.edu"},
  {"name":"Dayananda Sagar College","city":"Bangalore","state":"Karnataka","domain":"dayanandasagar.edu"},
  {"name":"Thapar Institute","city":"Patiala","state":"Punjab","domain":"thapar.edu"},
  {"name":"Amrita University","city":"Coimbatore","state":"Tamil Nadu","domain":"amrita.edu"},
  {"name":"Shiv Nadar University","city":"Greater Noida","state":"UP","domain":"snu.edu.in"},
  {"name":"KIIT School of Tech","city":"Bhubaneswar","state":"Odisha","domain":"kiit.ac.in"},
  {"name":"DAIICT","city":"Gandhinagar","state":"Gujarat","domain":"daiict.ac.in"},
  {"name":"Nirma University","city":"Ahmedabad","state":"Gujarat","domain":"nirmauni.ac.in"},
  {"name":"LD College of Engineering","city":"Ahmedabad","state":"Gujarat","domain":"ldce.ac.in"},
  {"name":"SPIT Mumbai","city":"Mumbai","state":"Maharashtra","domain":"spit.ac.in"},
  {"name":"VJTI Mumbai","city":"Mumbai","state":"Maharashtra","domain":"vjti.ac.in"},
  {"name":"KJ Somaiya","city":"Mumbai","state":"Maharashtra","domain":"somaiya.edu"},
  {"name":"PCCOE Pune","city":"Pune","state":"Maharashtra","domain":"pccoepune.com"},
  {"name":"VIIT Pune","city":"Pune","state":"Maharashtra","domain":"viit.ac.in"},
  {"name":"MIT WPU","city":"Pune","state":"Maharashtra","domain":"mitwpu.edu.in"},
  {"name":"Heritage Institute","city":"Kolkata","state":"West Bengal","domain":"heritageit.edu"},
  {"name":"Techno India","city":"Kolkata","state":"West Bengal","domain":"technoindiauniversity.ac.in"},
  {"name":"Haldia Institute","city":"Haldia","state":"West Bengal","domain":"hithaldia.ac.in"},
  {"name":"CV Raman Global University","city":"Bhubaneswar","state":"Odisha","domain":"cgu-odisha.ac.in"},
  {"name":"Silicon Institute","city":"Bhubaneswar","state":"Odisha","domain":"silicon.ac.in"},
  {"name":"ITER SOA","city":"Bhubaneswar","state":"Odisha","domain":"soa.ac.in"},
  {"name":"BIT Mesra","city":"Ranchi","state":"Jharkhand","domain":"bitmesra.ac.in"},
  {"name":"IIIT Ranchi","city":"Ranchi","state":"Jharkhand","domain":"iiitranchi.ac.in"},
  {"name":"IIIT Bhagalpur","city":"Bhagalpur","state":"Bihar","domain":"iiitbh.ac.in"},
  {"name":"Muzaffarpur Institute of Tech","city":"Muzaffarpur","state":"Bihar","domain":"mitmuzaffarpur.org"},
  {"name":"Bhagalpur College of Engg","city":"Bhagalpur","state":"Bihar","domain":"bcebhagalpur.ac.in"},
  {"name":"Amity University","city":"Noida","state":"UP","domain":"amity.edu"},
  {"name":"Sharda University","city":"Greater Noida","state":"UP","domain":"sharda.ac.in"},
  {"name":"Galgotias University","city":"Greater Noida","state":"UP","domain":"galgotiasuniversity.edu.in"},
  {"name":"LPU","city":"Phagwara","state":"Punjab","domain":"lpu.in"},
  {"name":"Chandigarh University","city":"Mohali","state":"Punjab","domain":"cumail.in"},
  {"name":"UPES","city":"Dehradun","state":"Uttarakhand","domain":"ddn.upes.ac.in"},
  {"name":"DIT University","city":"Dehradun","state":"Uttarakhand","domain":"dituniversity.edu.in"},
  {"name":"IIT Ropar","city":"Rupnagar","state":"Punjab","domain":"iitrpr.ac.in"},
  {"name":"IIT Gandhinagar","city":"Gandhinagar","state":"Gujarat","domain":"iitgn.ac.in"},
  {"name":"IIT Mandi","city":"Mandi","state":"Himachal Pradesh","domain":"iitmandi.ac.in"},
  {"name":"IIT Jodhpur","city":"Jodhpur","state":"Rajasthan","domain":"iitj.ac.in"},
  {"name":"IIT Patna","city":"Patna","state":"Bihar","domain":"iitp.ac.in"},
  {"name":"IIT Bhubaneswar","city":"Bhubaneswar","state":"Odisha","domain":"iitbbs.ac.in"},
  {"name":"IIT Tirupati","city":"Tirupati","state":"Andhra Pradesh","domain":"iittp.ac.in"},
  {"name":"IIT Palakkad","city":"Palakkad","state":"Kerala","domain":"iitpkd.ac.in"},
  {"name":"IIT Jammu","city":"Jammu","state":"Jammu & Kashmir","domain":"iitjammu.ac.in"},
  {"name":"IIT Dharwad","city":"Dharwad","state":"Karnataka","domain":"iitdh.ac.in"},
  {"name":"IIT Goa","city":"Goa","state":"Goa","domain":"iitgoa.ac.in"},
  {"name":"NIT Nagpur","city":"Nagpur","state":"Maharashtra","domain":"vnit.ac.in"},
  {"name":"NIT Bhopal","city":"Bhopal","state":"Madhya Pradesh","domain":"manit.ac.in"},
  {"name":"NIT Jaipur","city":"Jaipur","state":"Rajasthan","domain":"mnit.ac.in"},
  {"name":"NIT Allahabad","city":"Prayagraj","state":"Uttar Pradesh","domain":"mnnit.ac.in"},
  {"name":"NIT Kurukshetra","city":"Kurukshetra","state":"Haryana","domain":"nitkkr.ac.in"},
  {"name":"NIT Jamshedpur","city":"Jamshedpur","state":"Jharkhand","domain":"nitjsr.ac.in"},
  {"name":"NIT Hamirpur","city":"Hamirpur","state":"Himachal Pradesh","domain":"nith.ac.in"},
  {"name":"NIT Raipur","city":"Raipur","state":"Chhattisgarh","domain":"nitrr.ac.in"},
  {"name":"NIT Agartala","city":"Agartala","state":"Tripura","domain":"nita.ac.in"},
  {"name":"IIIT Gwalior","city":"Gwalior","state":"Madhya Pradesh","domain":"iiitm.ac.in"},
  {"name":"IIIT Jabalpur","city":"Jabalpur","state":"Madhya Pradesh","domain":"iiitdmj.ac.in"},
  {"name":"IIIT Lucknow","city":"Lucknow","state":"Uttar Pradesh","domain":"iiitl.ac.in"},
  {"name":"IIIT Pune","city":"Pune","state":"Maharashtra","domain":"iiitp.ac.in"},
  {"name":"IIIT Kota","city":"Kota","state":"Rajasthan","domain":"iiitkota.ac.in"},
  {"name":"IIIT Kancheepuram","city":"Chennai","state":"Tamil Nadu","domain":"iiitdm.ac.in"},
  {"name":"JNTU Hyderabad","city":"Hyderabad","state":"Telangana","domain":"jntuh.ac.in"},
  {"name":"Osmania University","city":"Hyderabad","state":"Telangana","domain":"osmania.ac.in"},
  {"name":"Andhra University","city":"Visakhapatnam","state":"Andhra Pradesh","domain":"andhrauniversity.edu.in"},
  {"name":"Punjab Engineering College","city":"Chandigarh","state":"Chandigarh","domain":"pec.ac.in"},
  {"name":"HBTU Kanpur","city":"Kanpur","state":"Uttar Pradesh","domain":"hbtu.ac.in"},
  {"name":"SGSITS Indore","city":"Indore","state":"Madhya Pradesh","domain":"sgsits.ac.in"},
  {"name":"MSU Baroda","city":"Vadodara","state":"Gujarat","domain":"msubaroda.ac.in"},
  {"name":"PSG College of Technology","city":"Coimbatore","state":"Tamil Nadu","domain":"psgtech.edu"},
  {"name":"CIT Coimbatore","city":"Coimbatore","state":"Tamil Nadu","domain":"cit.edu.in"},
  {"name":"SSN College of Engineering","city":"Chennai","state":"Tamil Nadu","domain":"ssn.edu.in"},
  {"name":"SASTRA University","city":"Thanjavur","state":"Tamil Nadu","domain":"sastra.edu"},
  {"name":"Walchand College of Engineering","city":"Sangli","state":"Maharashtra","domain":"walchandsangli.ac.in"},
  {"name":"Government College of Engineering Aurangabad","city":"Aurangabad","state":"Maharashtra","domain":"geca.ac.in"},
  {"name":"Charotar University (CHARUSAT)","city":"Anand","state":"Gujarat","domain":"charusat.ac.in"},
  {"name":"Tezpur University","city":"Tezpur","state":"Assam","domain":"tezu.ernet.in"},
  {"name":"Assam Engineering College","city":"Guwahati","state":"Assam","domain":"aec.ac.in"},
  {"name":"Jamia Millia Islamia","city":"Delhi","state":"Delhi","domain":"jmi.ac.in"},
  {"name":"Aligarh Muslim University","city":"Aligarh","state":"Uttar Pradesh","domain":"amu.ac.in"},
  {"name":"KIET Ghaziabad","city":"Ghaziabad","state":"Uttar Pradesh","domain":"kiet.edu"},
  {"name":"Ajay Kumar Garg Engineering College","city":"Ghaziabad","state":"Uttar Pradesh","domain":"akgec.ac.in"},
  {"name":"JSS Academy Noida","city":"Noida","state":"Uttar Pradesh","domain":"jssaten.ac.in"},
  {"name":"LNMIIT Jaipur","city":"Jaipur","state":"Rajasthan","domain":"lnmiit.ac.in"},
  {"name":"JECRC Jaipur","city":"Jaipur","state":"Rajasthan","domain":"jecrc.ac.in"},
  {"name":"RNS Institute of Technology","city":"Bangalore","state":"Karnataka","domain":"rnsit.ac.in"},
  {"name":"BNMIT Bangalore","city":"Bangalore","state":"Karnataka","domain":"bnmit.org"},
  {"name":"NIE Mysore","city":"Mysore","state":"Karnataka","domain":"nie.ac.in"},
  {"name":"JSS Science & Technology University","city":"Mysore","state":"Karnataka","domain":"jssstuniv.in"},
  {"name":"Velammal Engineering College","city":"Chennai","state":"Tamil Nadu","domain":"velammal.edu.in"},
  {"name":"Sri Sairam Engineering College","city":"Chennai","state":"Tamil Nadu","domain":"sairam.edu.in"},
  {"name":"Rajalakshmi Engineering College","city":"Chennai","state":"Tamil Nadu","domain":"rajalakshmi.org"},
  {"name":"Gokaraju Rangaraju Institute","city":"Hyderabad","state":"Telangana","domain":"griet.ac.in"},
  {"name":"Sreenidhi Institute","city":"Hyderabad","state":"Telangana","domain":"sreenidhi.edu.in"},
  {"name":"VNR VJIET","city":"Hyderabad","state":"Telangana","domain":"vnrvjiet.in"},
  {"name":"Narula Institute","city":"Kolkata","state":"West Bengal","domain":"narulainstitute.ac.in"},
  {"name":"GITA Bhubaneswar","city":"Bhubaneswar","state":"Odisha","domain":"gita.edu.in"},
  {"name":"Rungta College Bhilai","city":"Bhilai","state":"Chhattisgarh","domain":"rungta.ac.in"},
  {"name":"CSIT Durg","city":"Durg","state":"Chhattisgarh","domain":"csitdurg.in"},
  {"name":"Parul University","city":"Vadodara","state":"Gujarat","domain":"paruluniversity.ac.in"},
  {"name":"RK University","city":"Rajkot","state":"Gujarat","domain":"rku.ac.in"},
  {"name":"Shoolini University","city":"Solan","state":"Himachal Pradesh","domain":"shooliniuniversity.com"},
  {"name":"Chitkara University","city":"Baddi","state":"Himachal Pradesh","domain":"chitkara.edu.in"}
];

let sql = "INSERT INTO opp_colleges (name, code, university, city, state, email_domain, is_active) VALUES\n";

const values = [];
const seenDomains = new Set();
let idCounter = 1;

for (const c of APPROVED_COLLEGES) {
    if (seenDomains.has(c.domain)) continue;
    seenDomains.add(c.domain);
    
    // Generate a simple code (first letters of words or just name)
    const code = c.name.split(' ').map(w => w[0]).join('').toUpperCase().substring(0, 10);
    
    values.push(`('${c.name.replace(/'/g, "''")}', '${code}_${idCounter}', '${c.name.replace(/'/g, "''")}', '${c.city}', '${c.state}', '${c.domain}', true)`);
    idCounter++;
}

sql += values.join(",\n") + "\nON CONFLICT (code) DO NOTHING;";

fs.writeFileSync('c:/UNIQUE/Work/annnn/skilllinkr-opportunities/seed_colleges.sql', sql);
