INSERT INTO opp_colleges (name, code, university, city, state, email_domain, is_active) VALUES
('IIT Bombay', 'IB_1', 'IIT Bombay', 'Mumbai', 'Maharashtra', 'iitb.ac.in', true),
('IIT Delhi', 'ID_2', 'IIT Delhi', 'New Delhi', 'Delhi', 'iitd.ac.in', true),
('IIT Madras', 'IM_3', 'IIT Madras', 'Chennai', 'Tamil Nadu', 'iitm.ac.in', true),
('IIT Kanpur', 'IK_4', 'IIT Kanpur', 'Kanpur', 'Uttar Pradesh', 'iitk.ac.in', true),
('IIT Kharagpur', 'IK_5', 'IIT Kharagpur', 'Kharagpur', 'West Bengal', 'iitkgp.ac.in', true),
('IIT Roorkee', 'IR_6', 'IIT Roorkee', 'Roorkee', 'Uttarakhand', 'iitr.ac.in', true),
('IIT Guwahati', 'IG_7', 'IIT Guwahati', 'Guwahati', 'Assam', 'iitg.ac.in', true),
('IIT Hyderabad', 'IH_8', 'IIT Hyderabad', 'Hyderabad', 'Telangana', 'iith.ac.in', true),
('IIT BHU', 'IB_9', 'IIT BHU', 'Varanasi', 'Uttar Pradesh', 'iitbhu.ac.in', true),
('IIT Indore', 'II_10', 'IIT Indore', 'Indore', 'Madhya Pradesh', 'iiti.ac.in', true),
('NIT Trichy', 'NT_11', 'NIT Trichy', 'Tiruchirappalli', 'Tamil Nadu', 'nitt.edu', true),
('NIT Surathkal', 'NS_12', 'NIT Surathkal', 'Mangalore', 'Karnataka', 'nitk.edu.in', true),
('NIT Warangal', 'NW_13', 'NIT Warangal', 'Warangal', 'Telangana', 'nitw.ac.in', true),
('NIT Calicut', 'NC_14', 'NIT Calicut', 'Kozhikode', 'Kerala', 'nitc.ac.in', true),
('NIT Rourkela', 'NR_15', 'NIT Rourkela', 'Rourkela', 'Odisha', 'nitrkl.ac.in', true),
('NIT Patna', 'NP_16', 'NIT Patna', 'Patna', 'Bihar', 'nitp.ac.in', true),
('NIT Durgapur', 'ND_17', 'NIT Durgapur', 'Durgapur', 'West Bengal', 'nitdgp.ac.in', true),
('NIT Silchar', 'NS_18', 'NIT Silchar', 'Silchar', 'Assam', 'nits.ac.in', true),
('IIIT Hyderabad', 'IH_19', 'IIIT Hyderabad', 'Hyderabad', 'Telangana', 'iiit.ac.in', true),
('IIIT Bangalore', 'IB_20', 'IIIT Bangalore', 'Bangalore', 'Karnataka', 'iiitb.ac.in', true),
('IIIT Delhi', 'ID_21', 'IIIT Delhi', 'Delhi', 'Delhi', 'iiitd.ac.in', true),
('IIIT Allahabad', 'IA_22', 'IIIT Allahabad', 'Prayagraj', 'Uttar Pradesh', 'iiita.ac.in', true),
('BITS Pilani', 'BP_23', 'BITS Pilani', 'Pilani', 'Rajasthan', 'pilani.bits-pilani.ac.in', true),
('BITS Goa', 'BG_24', 'BITS Goa', 'Goa', 'Goa', 'goa.bits-pilani.ac.in', true),
('BITS Hyderabad', 'BH_25', 'BITS Hyderabad', 'Hyderabad', 'Telangana', 'hyderabad.bits-pilani.ac.in', true),
('VIT Vellore', 'VV_26', 'VIT Vellore', 'Vellore', 'Tamil Nadu', 'vitstudent.ac.in', true),
('SRM Institute', 'SI_27', 'SRM Institute', 'Chennai', 'Tamil Nadu', 'srmist.edu.in', true),
('Manipal Institute', 'MI_28', 'Manipal Institute', 'Manipal', 'Karnataka', 'learner.manipal.edu', true),
('KIIT', 'K_29', 'KIIT', 'Bhubaneswar', 'Odisha', 'kiit.ac.in', true),
('DTU', 'D_30', 'DTU', 'Delhi', 'Delhi', 'dtu.ac.in', true),
('NSUT', 'N_31', 'NSUT', 'Delhi', 'Delhi', 'nsut.ac.in', true),
('Jadavpur University', 'JU_32', 'Jadavpur University', 'Kolkata', 'West Bengal', 'jadavpuruniversity.in', true),
('Anna University', 'AU_33', 'Anna University', 'Chennai', 'Tamil Nadu', 'annauniv.edu', true),
('COEP', 'C_34', 'COEP', 'Pune', 'Maharashtra', 'coep.ac.in', true),
('RV College of Engineering', 'RCOE_35', 'RV College of Engineering', 'Bangalore', 'Karnataka', 'rvce.edu.in', true),
('BMS College of Engineering', 'BCOE_36', 'BMS College of Engineering', 'Bangalore', 'Karnataka', 'bmsce.ac.in', true),
('MS Ramaiah Institute', 'MRI_37', 'MS Ramaiah Institute', 'Bangalore', 'Karnataka', 'msrit.edu', true),
('PES University', 'PU_38', 'PES University', 'Bangalore', 'Karnataka', 'pes.edu', true),
('Dayananda Sagar College', 'DSC_39', 'Dayananda Sagar College', 'Bangalore', 'Karnataka', 'dayanandasagar.edu', true),
('Thapar Institute', 'TI_40', 'Thapar Institute', 'Patiala', 'Punjab', 'thapar.edu', true),
('Amrita University', 'AU_41', 'Amrita University', 'Coimbatore', 'Tamil Nadu', 'amrita.edu', true),
('Shiv Nadar University', 'SNU_42', 'Shiv Nadar University', 'Greater Noida', 'UP', 'snu.edu.in', true),
('DAIICT', 'D_43', 'DAIICT', 'Gandhinagar', 'Gujarat', 'daiict.ac.in', true),
('Nirma University', 'NU_44', 'Nirma University', 'Ahmedabad', 'Gujarat', 'nirmauni.ac.in', true),
('LD College of Engineering', 'LCOE_45', 'LD College of Engineering', 'Ahmedabad', 'Gujarat', 'ldce.ac.in', true),
('SPIT Mumbai', 'SM_46', 'SPIT Mumbai', 'Mumbai', 'Maharashtra', 'spit.ac.in', true),
('VJTI Mumbai', 'VM_47', 'VJTI Mumbai', 'Mumbai', 'Maharashtra', 'vjti.ac.in', true),
('KJ Somaiya', 'KS_48', 'KJ Somaiya', 'Mumbai', 'Maharashtra', 'somaiya.edu', true),
('PCCOE Pune', 'PP_49', 'PCCOE Pune', 'Pune', 'Maharashtra', 'pccoepune.com', true),
('VIIT Pune', 'VP_50', 'VIIT Pune', 'Pune', 'Maharashtra', 'viit.ac.in', true),
('MIT WPU', 'MW_51', 'MIT WPU', 'Pune', 'Maharashtra', 'mitwpu.edu.in', true),
('Heritage Institute', 'HI_52', 'Heritage Institute', 'Kolkata', 'West Bengal', 'heritageit.edu', true),
('Techno India', 'TI_53', 'Techno India', 'Kolkata', 'West Bengal', 'technoindiauniversity.ac.in', true),
('Haldia Institute', 'HI_54', 'Haldia Institute', 'Haldia', 'West Bengal', 'hithaldia.ac.in', true),
('CV Raman Global University', 'CRGU_55', 'CV Raman Global University', 'Bhubaneswar', 'Odisha', 'cgu-odisha.ac.in', true),
('Silicon Institute', 'SI_56', 'Silicon Institute', 'Bhubaneswar', 'Odisha', 'silicon.ac.in', true),
('ITER SOA', 'IS_57', 'ITER SOA', 'Bhubaneswar', 'Odisha', 'soa.ac.in', true),
('BIT Mesra', 'BM_58', 'BIT Mesra', 'Ranchi', 'Jharkhand', 'bitmesra.ac.in', true),
('IIIT Ranchi', 'IR_59', 'IIIT Ranchi', 'Ranchi', 'Jharkhand', 'iiitranchi.ac.in', true),
('IIIT Bhagalpur', 'IB_60', 'IIIT Bhagalpur', 'Bhagalpur', 'Bihar', 'iiitbh.ac.in', true),
('Muzaffarpur Institute of Tech', 'MIOT_61', 'Muzaffarpur Institute of Tech', 'Muzaffarpur', 'Bihar', 'mitmuzaffarpur.org', true),
('Bhagalpur College of Engg', 'BCOE_62', 'Bhagalpur College of Engg', 'Bhagalpur', 'Bihar', 'bcebhagalpur.ac.in', true),
('Amity University', 'AU_63', 'Amity University', 'Noida', 'UP', 'amity.edu', true),
('Sharda University', 'SU_64', 'Sharda University', 'Greater Noida', 'UP', 'sharda.ac.in', true),
('Galgotias University', 'GU_65', 'Galgotias University', 'Greater Noida', 'UP', 'galgotiasuniversity.edu.in', true),
('LPU', 'L_66', 'LPU', 'Phagwara', 'Punjab', 'lpu.in', true),
('Chandigarh University', 'CU_67', 'Chandigarh University', 'Mohali', 'Punjab', 'cumail.in', true),
('UPES', 'U_68', 'UPES', 'Dehradun', 'Uttarakhand', 'ddn.upes.ac.in', true),
('DIT University', 'DU_69', 'DIT University', 'Dehradun', 'Uttarakhand', 'dituniversity.edu.in', true),
('IIT Ropar', 'IR_70', 'IIT Ropar', 'Rupnagar', 'Punjab', 'iitrpr.ac.in', true),
('IIT Gandhinagar', 'IG_71', 'IIT Gandhinagar', 'Gandhinagar', 'Gujarat', 'iitgn.ac.in', true),
('IIT Mandi', 'IM_72', 'IIT Mandi', 'Mandi', 'Himachal Pradesh', 'iitmandi.ac.in', true),
('IIT Jodhpur', 'IJ_73', 'IIT Jodhpur', 'Jodhpur', 'Rajasthan', 'iitj.ac.in', true),
('IIT Patna', 'IP_74', 'IIT Patna', 'Patna', 'Bihar', 'iitp.ac.in', true),
('IIT Bhubaneswar', 'IB_75', 'IIT Bhubaneswar', 'Bhubaneswar', 'Odisha', 'iitbbs.ac.in', true),
('IIT Tirupati', 'IT_76', 'IIT Tirupati', 'Tirupati', 'Andhra Pradesh', 'iittp.ac.in', true),
('IIT Palakkad', 'IP_77', 'IIT Palakkad', 'Palakkad', 'Kerala', 'iitpkd.ac.in', true),
('IIT Jammu', 'IJ_78', 'IIT Jammu', 'Jammu', 'Jammu & Kashmir', 'iitjammu.ac.in', true),
('IIT Dharwad', 'ID_79', 'IIT Dharwad', 'Dharwad', 'Karnataka', 'iitdh.ac.in', true),
('IIT Goa', 'IG_80', 'IIT Goa', 'Goa', 'Goa', 'iitgoa.ac.in', true),
('NIT Nagpur', 'NN_81', 'NIT Nagpur', 'Nagpur', 'Maharashtra', 'vnit.ac.in', true),
('NIT Bhopal', 'NB_82', 'NIT Bhopal', 'Bhopal', 'Madhya Pradesh', 'manit.ac.in', true),
('NIT Jaipur', 'NJ_83', 'NIT Jaipur', 'Jaipur', 'Rajasthan', 'mnit.ac.in', true),
('NIT Allahabad', 'NA_84', 'NIT Allahabad', 'Prayagraj', 'Uttar Pradesh', 'mnnit.ac.in', true),
('NIT Kurukshetra', 'NK_85', 'NIT Kurukshetra', 'Kurukshetra', 'Haryana', 'nitkkr.ac.in', true),
('NIT Jamshedpur', 'NJ_86', 'NIT Jamshedpur', 'Jamshedpur', 'Jharkhand', 'nitjsr.ac.in', true),
('NIT Hamirpur', 'NH_87', 'NIT Hamirpur', 'Hamirpur', 'Himachal Pradesh', 'nith.ac.in', true),
('NIT Raipur', 'NR_88', 'NIT Raipur', 'Raipur', 'Chhattisgarh', 'nitrr.ac.in', true),
('NIT Agartala', 'NA_89', 'NIT Agartala', 'Agartala', 'Tripura', 'nita.ac.in', true),
('IIIT Gwalior', 'IG_90', 'IIIT Gwalior', 'Gwalior', 'Madhya Pradesh', 'iiitm.ac.in', true),
('IIIT Jabalpur', 'IJ_91', 'IIIT Jabalpur', 'Jabalpur', 'Madhya Pradesh', 'iiitdmj.ac.in', true),
('IIIT Lucknow', 'IL_92', 'IIIT Lucknow', 'Lucknow', 'Uttar Pradesh', 'iiitl.ac.in', true),
('IIIT Pune', 'IP_93', 'IIIT Pune', 'Pune', 'Maharashtra', 'iiitp.ac.in', true),
('IIIT Kota', 'IK_94', 'IIIT Kota', 'Kota', 'Rajasthan', 'iiitkota.ac.in', true),
('IIIT Kancheepuram', 'IK_95', 'IIIT Kancheepuram', 'Chennai', 'Tamil Nadu', 'iiitdm.ac.in', true),
('JNTU Hyderabad', 'JH_96', 'JNTU Hyderabad', 'Hyderabad', 'Telangana', 'jntuh.ac.in', true),
('Osmania University', 'OU_97', 'Osmania University', 'Hyderabad', 'Telangana', 'osmania.ac.in', true),
('Andhra University', 'AU_98', 'Andhra University', 'Visakhapatnam', 'Andhra Pradesh', 'andhrauniversity.edu.in', true),
('Punjab Engineering College', 'PEC_99', 'Punjab Engineering College', 'Chandigarh', 'Chandigarh', 'pec.ac.in', true),
('HBTU Kanpur', 'HK_100', 'HBTU Kanpur', 'Kanpur', 'Uttar Pradesh', 'hbtu.ac.in', true),
('SGSITS Indore', 'SI_101', 'SGSITS Indore', 'Indore', 'Madhya Pradesh', 'sgsits.ac.in', true),
('MSU Baroda', 'MB_102', 'MSU Baroda', 'Vadodara', 'Gujarat', 'msubaroda.ac.in', true),
('PSG College of Technology', 'PCOT_103', 'PSG College of Technology', 'Coimbatore', 'Tamil Nadu', 'psgtech.edu', true),
('CIT Coimbatore', 'CC_104', 'CIT Coimbatore', 'Coimbatore', 'Tamil Nadu', 'cit.edu.in', true),
('SSN College of Engineering', 'SCOE_105', 'SSN College of Engineering', 'Chennai', 'Tamil Nadu', 'ssn.edu.in', true),
('SASTRA University', 'SU_106', 'SASTRA University', 'Thanjavur', 'Tamil Nadu', 'sastra.edu', true),
('Walchand College of Engineering', 'WCOE_107', 'Walchand College of Engineering', 'Sangli', 'Maharashtra', 'walchandsangli.ac.in', true),
('Government College of Engineering Aurangabad', 'GCOEA_108', 'Government College of Engineering Aurangabad', 'Aurangabad', 'Maharashtra', 'geca.ac.in', true),
('Charotar University (CHARUSAT)', 'CU(_109', 'Charotar University (CHARUSAT)', 'Anand', 'Gujarat', 'charusat.ac.in', true),
('Tezpur University', 'TU_110', 'Tezpur University', 'Tezpur', 'Assam', 'tezu.ernet.in', true),
('Assam Engineering College', 'AEC_111', 'Assam Engineering College', 'Guwahati', 'Assam', 'aec.ac.in', true),
('Jamia Millia Islamia', 'JMI_112', 'Jamia Millia Islamia', 'Delhi', 'Delhi', 'jmi.ac.in', true),
('Aligarh Muslim University', 'AMU_113', 'Aligarh Muslim University', 'Aligarh', 'Uttar Pradesh', 'amu.ac.in', true),
('KIET Ghaziabad', 'KG_114', 'KIET Ghaziabad', 'Ghaziabad', 'Uttar Pradesh', 'kiet.edu', true),
('Ajay Kumar Garg Engineering College', 'AKGEC_115', 'Ajay Kumar Garg Engineering College', 'Ghaziabad', 'Uttar Pradesh', 'akgec.ac.in', true),
('JSS Academy Noida', 'JAN_116', 'JSS Academy Noida', 'Noida', 'Uttar Pradesh', 'jssaten.ac.in', true),
('LNMIIT Jaipur', 'LJ_117', 'LNMIIT Jaipur', 'Jaipur', 'Rajasthan', 'lnmiit.ac.in', true),
('JECRC Jaipur', 'JJ_118', 'JECRC Jaipur', 'Jaipur', 'Rajasthan', 'jecrc.ac.in', true),
('RNS Institute of Technology', 'RIOT_119', 'RNS Institute of Technology', 'Bangalore', 'Karnataka', 'rnsit.ac.in', true),
('BNMIT Bangalore', 'BB_120', 'BNMIT Bangalore', 'Bangalore', 'Karnataka', 'bnmit.org', true),
('NIE Mysore', 'NM_121', 'NIE Mysore', 'Mysore', 'Karnataka', 'nie.ac.in', true),
('JSS Science & Technology University', 'JS&TU_122', 'JSS Science & Technology University', 'Mysore', 'Karnataka', 'jssstuniv.in', true),
('Velammal Engineering College', 'VEC_123', 'Velammal Engineering College', 'Chennai', 'Tamil Nadu', 'velammal.edu.in', true),
('Sri Sairam Engineering College', 'SSEC_124', 'Sri Sairam Engineering College', 'Chennai', 'Tamil Nadu', 'sairam.edu.in', true),
('Rajalakshmi Engineering College', 'REC_125', 'Rajalakshmi Engineering College', 'Chennai', 'Tamil Nadu', 'rajalakshmi.org', true),
('Gokaraju Rangaraju Institute', 'GRI_126', 'Gokaraju Rangaraju Institute', 'Hyderabad', 'Telangana', 'griet.ac.in', true),
('Sreenidhi Institute', 'SI_127', 'Sreenidhi Institute', 'Hyderabad', 'Telangana', 'sreenidhi.edu.in', true),
('VNR VJIET', 'VV_128', 'VNR VJIET', 'Hyderabad', 'Telangana', 'vnrvjiet.in', true),
('Narula Institute', 'NI_129', 'Narula Institute', 'Kolkata', 'West Bengal', 'narulainstitute.ac.in', true),
('GITA Bhubaneswar', 'GB_130', 'GITA Bhubaneswar', 'Bhubaneswar', 'Odisha', 'gita.edu.in', true),
('Rungta College Bhilai', 'RCB_131', 'Rungta College Bhilai', 'Bhilai', 'Chhattisgarh', 'rungta.ac.in', true),
('CSIT Durg', 'CD_132', 'CSIT Durg', 'Durg', 'Chhattisgarh', 'csitdurg.in', true),
('Parul University', 'PU_133', 'Parul University', 'Vadodara', 'Gujarat', 'paruluniversity.ac.in', true),
('RK University', 'RU_134', 'RK University', 'Rajkot', 'Gujarat', 'rku.ac.in', true),
('Shoolini University', 'SU_135', 'Shoolini University', 'Solan', 'Himachal Pradesh', 'shooliniuniversity.com', true),
('Chitkara University', 'CU_136', 'Chitkara University', 'Baddi', 'Himachal Pradesh', 'chitkara.edu.in', true)
ON CONFLICT (code) DO NOTHING;